osx_image: xcode10.2
language: objective-c
script:
  - xcodebuild -project Demo.xcodeproj -scheme SwiftDemo      -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty
  - xcodebuild -project Demo.xcodeproj -scheme ObjectiveCDemo -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty
  - xcodebuild -project Demo.xcodeproj -scheme Tests          -destination 'platform=iOS Simulator,name=iPhone 8' test  | xcpretty
notifications:
  email: false
